spring:
  application:
    name: AUTH-SERVICE
  cloud:
    stream:
      bindings:
        userCreatedOutput-out-0:
          destination: userCreatedOutput
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400
