server:
  port: 9999
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: files
          uri: lb://FILES-SERVICE
          predicates:
            - Path=/files/**
        - id: authorizations
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
        - id: movies
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/movies/**
  main:
    web-application-type: reactive
  config:
    activate:
      on-profile: dev
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: files
          uri: lb://FILES-SERVICE
          predicates:
            - Path=/files/**
        - id: authorizations
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
        - id: movies
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/movies/**
  main:
    web-application-type: reactive
  config:
    activate:
      on-profile: test
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: files
          uri: lb://FILES-SERVICE
          predicates:
            - Path=/files/**
        - id: authorizations
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
        - id: movies
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/movies/**
  main:
    web-application-type: reactive
  config:
    activate:
      on-profile: prod
